Cf.Dotnet.Architecture.Application.Web/Models/BuyerModel.cs
namespace Cf.Dotnet.Architecture.Application.Models;

public sealed record BuyerModel(int Id, string Name, decimal Balance);

Cf.Dotnet.Architecture.Application.Web/Models/OrderItemsModel.cs
using Cf.Dotnet.Architecture.Domain.Enums;

namespace Cf.Dotnet.Architecture.Application.Models;

public sealed record OrdersSummary(int Id, OrderStatus Status, decimal Total, string BuyerName);

Cf.Dotnet.Architecture.Application.Web/Controllers/BuyerController.cs
using AutoMapper;
using Cf.Dotnet.Architecture.Application.Models;
using Cf.Dotnet.Architecture.Domain.Entities;
using Cf.DotnetArchitecture.SeedWork;
using Microsoft.AspNetCore.Mvc;

namespace Cf.Dotnet.Architecture.Application.Controllers;

public class BuyerController : Controller
{
    private readonly IRepository<Buyer> buyerRepository;
    private readonly IMapper mapper;

    public BuyerController(IRepository<Buyer> buyerRepository, IMapper mapper)
    {
        this.mapper = mapper;
        this.buyerRepository = buyerRepository;
    }

    public async Task<ViewResult> Index()
    {
        var result = await buyerRepository.ToListAsync();
        var items = mapper.Map<List<BuyerModel>>(result);
        return View(items);
    }
}

Cf.Dotnet.Architecture.Application.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cf.Dotnet.Architecture.Application.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

Cf.Dotnet.Architecture.Application.Web/Controllers/OrderSummaryController.cs
using Cf.Dotnet.Architecture.Application.Services;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Cf.Dotnet.Architecture.Application.Controllers;

public class OrderSummaryController : Controller
{
    private readonly IMediator mediator;

    public OrderSummaryController(IMediator mediator)
    {
        this.mediator = mediator;
    }

    public async Task<IActionResult> Index()
    {
        var ordersSummaries = await mediator.Send(new GetOrdersSummaryService());
        return View(ordersSummaries);
    }

    public async Task<IActionResult> Confirm(int id)
    {
        await mediator.Send(new ConfirmOrderService(id));
        return RedirectToAction(nameof(Index));
    }
}

Cf.Dotnet.Architecture.Application.Web/Views/Buyer/Index.cshtml
@model IEnumerable<BuyerModel>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Balance</td>
        </tr>
    }
    </tbody>
</table>

Cf.Dotnet.Architecture.Application.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Cf.Dotnet.Architecture.Application.Web/Views/OrderSummary/Index.cshtml
@model IEnumerable<OrdersSummary>

<table class="table">
    <thead>
    <tr>
        <th>
            ID
        </th>
        <th>
            Estado
        </th>
        <th>
            Total
        </th>
        <th>
            Comprador
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Status</td>
            <td>@item.Total</td>
            <td>@item.BuyerName</td>
            <td>
                <form method="post" asp-action="Confirm">
                    <input type="hidden" name="Id" value="@item.Id"/>
                    <input type="submit" value="Confirmar" class="btn btn-primary"/>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

Cf.Dotnet.Architecture.Application.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Cf.Dotnet.Architecture.Application.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Cf.Dotnet.Architecture.Application.Web.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cf.Dotnet.Architecture.Application.Web</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="OrderSummary" asp-action="Index">Ordenes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Buyer" asp-action="Index">Compradores</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>